### PR TITLE
Convert internal CTCSS/DCS code to a human recongnizable value

### LINKED ISSUE #3: Mapping of ctcss
I see the bct125a is returning integers for the ctcss values.  Are you aware of a mapping anywhere?

eg, I set the ctcss to 225.7 in the radio and the resulting json/csv has 108.

Great stuff btw, nice clean code too.

```
Reading from scanner...
> /home/bthornto/github/bc125/venv/lib64/python3.11/site-packages/bc125py/sdo.py(720)from_command_response()
-> self.index = int(command_response[0])
(Pdb) command_response
('1', 'Steve net', '04627000', 'AUTO', '108', '2', '0', '1')
(Pdb) 
```

### PR DESCRIPTION
**Pull request by cidrblock**
Closes #3 

- Rather than the user needing to reference the protocol document to convert CTCSS/DCS value to the radios internal values, store the mapping in a dictionary and reference during loading and writing.
- Provide a friendly message when the user provided value is not valid.
- Allow for some case and variation of string values

Doc strings, type hints, and unit tests included.

LMK if you were thinking about doing this differently

Brad

### CODE REVIEW

**Comment by itsmaxymoo** [comment]
Thanks for the contribution! My only concern is that this implementation breaks backwards compatibility with the current file format. I think it would be best if raw integer values in configs were just passed through to the scanner, and the new human-friendly strings were additionally prefixed with "ctcss"/"dcs"...

Finally, I think it would be best to have the conversion in the `to_dict` and `from_dict` functions. This is to help the humans after all, and that would define a better separation of responsibilities.

**Comment by cidrblock** [comment]
Thank for taking the time to review.

I've made the change to using `to_dict` and `from_dict` as suggested, it is indeed cleaner.

With regard to backward compatibility, I had originally considered supported both but a round-trip import/export might not be exact and therefore introduce some confusion to the user.  Might a suggest a major release here with accompaning release notes explaining new files would need to be authored using the human-friendly value and exisiting file updated or re-imported from the radio?

I do a lot of cutting and pasting between CSVs for various radios chirp, oem cps and now bc125py.  A simple re-import to switch from the internals to the human-friendly was my preference rather than having to always prefix the values when moving data around.

Thank you again for this, I didn't have to break out the other laptop to program the scanner.

**Comment by itsmaxymoo** [comment]
I'm sorry, but after careful consideration I just cannot accept these changes. After mulling over the codebase, I have determined that this feature would require a partial rewrite to be implemented to the best degree of flexibility. However, I am not saying no!

I would like if you submitted a PR for just mappings.py and your tests module. Ultimately I think the program needs to be rewritten to perform input validation in the from_dict function (for all SDOs) as opposed to a separate validate() function.

This is a task I am willing to take on. I really appreciate your work compiling the integer to string mappings as well as implementing tests. That's something I should've done from the start!

**Comment by cidrblock** [comment]
PR is up, I hope those are useful.

I'll keep an eye out for the next release and your PR to see where you are headed.

Thanks again,

Brad

**Pull request closed without merging**
